export {default as Home} from './Home/Home';
export {default as Category} from './Category/Category';
export {default as SingleProd} from './SingleProd/SingleProd';
export {default as Cart} from './Cart/Cart';
export {default as Checkout} from './Checkout/Checkout';
export {default as ThankYou} from './ThankYou/ThankYou';
export {default as PrivacyPolicy} from './PrivacyPolicy/PrivacyPolicy';
export {default as TnC} from './TnC/TnC';
export {default as Disclaimer} from './Disclaimer/Disclaimer';